name: Notebooks

on:
    push:
      branches: [ develop ]
    pull_request:
      branches: [ main, develop ]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Initialize Python
          uses: actions/setup-python@v4.3.1
          with:
            python-version: '3.11'
        - name: Setup Python
          run: |
            python -m pip install --upgrade pip jupyter
            python -m pip install .
            python -m ipykernel install --user --name run-notebook --display-name "Run notebook"
        - name: Run notebooks
          run: |
            # The functional annotation of RPGRIP1, STXBP1, and KBG takes too long.
            # However, we can add them later, if we will really want that.
            cohorts=(MAPK8IP3 PPP2R1A SUOX)
            for cohort in ${cohorts[@]}; do
              nb="notebooks/${cohort}/${cohort}.ipynb"
              printf "Processing notebook at %s\n" ${nb}
              jupyter execute --kernel_name run-notebook ${nb}
            done
